name = "navsphere"
compatibility_date = "2024-11-11"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[env.production.vars]
GITHUB_CLIENT_ID = "Ov23lisT99QBdWOP0T1L"
GITHUB_OWNER = "ddxl1207"
GITHUB_REPO = "navsphere"
GITHUB_BRANCH = "main"
NEXTAUTH_URL = "https://navsphere-96i.pages.dev/api/auth"
NEXT_PUBLIC_API_URL="https://navsphere-96i.pages.dev/"

